name: SFTP Docker Image build

on:
    push:
        branches:
            - dev
            - staging
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: login to DEV azure registry
              if: github.ref == 'refs/heads/dev'
              uses: azure/docker-login@v1
              with:
                  login-server: fmcappdev.azurecr.io
                  username: ${{ secrets.DEV_REGISTRY_USERNAME }}
                  password: ${{ secrets.DEV_REGISTRY_PASSWORD }}
            - name: build & push DEV container
              if: github.ref == 'refs/heads/dev'
              run: |
                docker build . -t fmcappdev.azurecr.io/sftp:latest
                docker push fmcappdev.azurecr.io/sftp:latest
            - name: login to PROD azure registry
              if: github.ref == 'refs/heads/master'
              uses: azure/docker-login@v1
              with:
                  login-server: pestdetectioncr.azurecr.io
                  username: ${{ secrets.PROD_REGISTRY_USERNAME }}
                  password: ${{ secrets.PROD_REGISTRY_PASSWORD }}
            - name: build & push PROD container
              if: github.ref == 'refs/heads/master'
              run: |
                docker build . -t pestdetectioncr.azurecr.io/sftp:latest
                docker push pestdetectioncr.azurecr.io/sftp:latest

